import { AlertTriangle, Check, Plug, RefreshCw, Server, Sparkles, TerminalSquare } from "lucide-react";
import { useEffect, useState } from "react";
import { appApi } from "../api/bridge";
import { Badge, EmptyState, ErrorState, LoadingState, PageHeader, PathText } from "../components/ui";
import { getAgentLabel } from "../config/agents";
import { useAppStore } from "../store/appStore";
import type { ConfigurationInventory } from "../types/models";

export default function ConfigurationsPage() {
  const { projects, loadProjects, notify } = useAppStore(); const [projectId, setProjectId] = useState(""); const [inventory, setInventory] = useState<ConfigurationInventory | null>(null); const [error, setError] = useState<string | null>(null); const [scanning, setScanning] = useState(false); const [tab, setTab] = useState<"skills" | "mcp" | "instructions">("skills");
  useEffect(() => { void loadProjects(); }, [loadProjects]);
  async function scan() { setScanning(true); try { setInventory(await appApi.scanConfigurations(projectId || undefined)); setError(null); } catch (reason) { setError(reason instanceof Error ? reason.message : String(reason)); } finally { setScanning(false); } }
  useEffect(() => { void scan(); }, [projectId]);
  async function bind(kind: "skill" | "mcp", itemId: string, bound: boolean) { if (!projectId) { notify({ tone: "info", title: "请先选择统一项目" }); return; } await appApi.bindConfiguration(projectId, kind, itemId, bound); await scan(); notify({ tone: "success", title: bound ? "配置已绑定" : "配置已解绑" }); }
  return <div className="page configurations-page"><PageHeader eyebrow="DISCOVERY & BINDINGS" title="Skills 与配置" description="发现本机 Codex Skills、MCP Servers 和自定义指令；只展示与绑定，不自动改写第三方配置。" actions={<><label className="project-filter"><span>绑定目标</span><select value={projectId} onChange={(event) => setProjectId(event.target.value)}><option value="">仅查看，不绑定</option>{projects.filter((project) => !project.archived).map((project) => <option value={project.id} key={project.id}>{project.name}</option>)}</select></label><button className="button button-primary" onClick={() => void scan()} disabled={scanning}><RefreshCw size={14} className={scanning ? "animate-spin" : ""} />重新发现</button></>} />
    <div className="tabs" role="tablist">{([['skills','Skills'],['mcp','MCP Servers'],['instructions','自定义指令']] as const).map(([id,label]) => <button key={id} className={tab === id ? "active" : ""} onClick={() => setTab(id)} role="tab" aria-selected={tab === id}>{label}</button>)}</div>
    {scanning && !inventory ? <LoadingState label="正在扫描本机 Agent 配置" /> : error ? <ErrorState message={error} onRetry={() => void scan()} /> : inventory && <section className="configuration-content">
      {tab === "skills" && (inventory.skills.length ? <div className="config-list">{inventory.skills.map((skill) => <article key={skill.id}><div className="config-icon"><Sparkles size={17} /></div><div><header><strong>{skill.name}</strong><Badge tone="signal">{skill.sourcePlatform}</Badge><Badge tone={skill.installationState === "available" ? "success" : "warning"}>{skill.installationState}</Badge></header><p>{skill.description}</p><PathText value={skill.sourcePath} /><div className="compat-line">兼容：{skill.compatibleAgents.map(getAgentLabel).join(" · ") || "尚未评估"}</div></div><button className={`button ${skill.bound ? "button-secondary" : "button-primary"}`} disabled={!projectId} onClick={() => void bind("skill", skill.id, !skill.bound)}>{skill.bound ? <><Check size={13} />已绑定</> : "绑定到项目"}</button></article>)}</div> : <EmptyState icon={<Sparkles size={22} />} title="未发现 Skills" detail="已检查 ~/.codex/skills 和 ~/.agents/skills，不会创建演示配置。" />)}
      {tab === "mcp" && (inventory.mcpServers.length ? <div className="config-list">{inventory.mcpServers.map((server) => <article key={server.id}><div className="config-icon"><Server size={17} /></div><div><header><strong>{server.name}</strong><Badge>{getAgentLabel(server.sourceAgent)}</Badge><Badge tone="signal">{server.transport}</Badge></header><p>{server.command || "配置未暴露 command 字段"}</p><div className="compat-line">兼容：{server.compatibleAgents.map(getAgentLabel).join(" · ")}</div></div><button className={`button ${server.bound ? "button-secondary" : "button-primary"}`} disabled={!projectId} onClick={() => void bind("mcp", server.id, !server.bound)}>{server.bound ? <><Check size={13} />已绑定</> : "绑定到项目"}</button></article>)}</div> : <EmptyState icon={<Plug size={22} />} title="未发现 MCP Servers" detail="Codex config.toml 中没有可解析的 mcp_servers 配置。" />)}
      {tab === "instructions" && (inventory.customInstructions.length ? <div className="config-list">{inventory.customInstructions.map((instruction) => <article key={instruction.id}><div className="config-icon"><TerminalSquare size={17} /></div><div><header><strong>{instruction.name}</strong><Badge>{getAgentLabel(instruction.sourceAgent)}</Badge></header><PathText value={instruction.path} /><p className="warning-copy"><AlertTriangle size={13} />第一版只发现和展示；不会自动合并或覆盖指令文件。</p></div></article>)}</div> : <EmptyState icon={<TerminalSquare size={22} />} title="未发现自定义指令" detail="没有找到可读取的 AGENTS.md。" />)}
    </section>}
  </div>;
}
